title: Jingtao Tang
description: Jingtao Tang's Homepage
logo: /assets/img/avatar.png
remote_theme: pages-themes/minimal@v0.2.0
email: todd.j.tang@gmail.com
github_username: reso1
show_downloads: false
github:
  is_project_page: false
  is_user_page: false
